# refer: https://github.com/dependabot/dependabot-core/blob/main/.github/dependabot.yml
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "03:22"
      timezone: "Europe/London"
