---
version: '3'

# This Taskfile represents the primary control surface for developers interacting with
# this component.
#
# Primary "configure/build/deploy/test" tasks must be provided directly in this top level
# taskfile
#
# Infrequently used or pure sub-tasks should be in subservient taskfiles and included
# here.
#
# All tasks that are expected to be run directly by developers must have a meaningful
# 'desc' with all optional variables defined, in this file or in included files.
#
# All tasks that are internal sub-tasks only should have a meaningful 'summary'.
#
includes:
  codeqa:
    taskfile: ./taskfiles/Taskfile_codeqa.yml
  mocks:
    taskfile: ./taskfiles/Taskfile_mocks.yml

tasks:

  codeqa:
    desc: |
      format the source and run all the quality checks
      (Does not run unit tests)
    cmds:
      - task: codeqa:format
      - task: codeqa:lint
      - task: codeqa:vulncheck

  build:
    desc: ensure go build works for all packages
    cmds:
      - go build -v ./...

  test:
    desc: run the tests
    cmds:
      - task: codeqa:test
