// Maintainers, please refer to the style guide here:
//     https://developers.google.com/protocol-buffers/docs/style

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: datatrails-common-api/assets/v2/assets/assetresponse.proto

package assets

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	attribute "github.com/datatrails/go-datatrails-simplehash/go-datatrails-common-api-gen/attribute/v2/attribute"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The full set of properties common to all assets. Note that some of these properies are synthesized by the system. Individual apis will clarify which properties the accept and require. Assets may have one or more representative images. Those will be included in the attachments list. The label for those attachements is up to the UI
// Note that there is no PATCH or PUT for assets as they are immutable and "changes" are merely aggregated events on the identified asset, therefore mutable fields; display_name, extended_attributes, type_attributes, tracked and attachments, will each require an Event to change (see Events below).
type AssetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// asset identity
	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// list of enabled behaviours
	Behaviours []string `protobuf:"bytes,2,rep,name=behaviours,proto3" json:"behaviours,omitempty"`
	// all the assets attributes
	Attributes map[string]*attribute.Attribute `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// indicated if asset has been committed to the blockchain, possible values are CONFIRMED for committed, PENDING for not yet committed or FAILED for permanent failure
	ConfirmationStatus ConfirmationStatus `protobuf:"varint,4,opt,name=confirmation_status,json=confirmationStatus,proto3,enum=archivist.v2.ConfirmationStatus" json:"confirmation_status,omitempty"`
	// indicates if asset is being tracked in the system TRACKED or NOT_TRACKED
	Tracked TrackedStatus `protobuf:"varint,5,opt,name=tracked,proto3,enum=archivist.v2.TrackedStatus" json:"tracked,omitempty"`
	// describes the access policy for this asset
	AccessPolicy map[string]*attribute.Attribute `protobuf:"bytes,6,rep,name=access_policy,json=accessPolicy,proto3" json:"access_policy,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// wallet address for the owner of this asset
	Owner          string                 `protobuf:"bytes,7,opt,name=owner,proto3" json:"owner,omitempty"`
	AtTime         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=at_time,json=atTime,proto3" json:"at_time,omitempty"`
	ProofMechanism ProofMechanism         `protobuf:"varint,10,opt,name=proof_mechanism,json=proofMechanism,proto3,enum=archivist.v2.ProofMechanism" json:"proof_mechanism,omitempty"`
	ChainId        string                 `protobuf:"bytes,11,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Public         bool                   `protobuf:"varint,12,opt,name=public,proto3" json:"public,omitempty"`
	TenantIdentity string                 `protobuf:"bytes,13,opt,name=tenant_identity,json=tenantIdentity,proto3" json:"tenant_identity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssetResponse) Reset() {
	*x = AssetResponse{}
	mi := &file_datatrails_common_api_assets_v2_assets_assetresponse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetResponse) ProtoMessage() {}

func (x *AssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datatrails_common_api_assets_v2_assets_assetresponse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetResponse.ProtoReflect.Descriptor instead.
func (*AssetResponse) Descriptor() ([]byte, []int) {
	return file_datatrails_common_api_assets_v2_assets_assetresponse_proto_rawDescGZIP(), []int{0}
}

func (x *AssetResponse) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *AssetResponse) GetBehaviours() []string {
	if x != nil {
		return x.Behaviours
	}
	return nil
}

func (x *AssetResponse) GetAttributes() map[string]*attribute.Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *AssetResponse) GetConfirmationStatus() ConfirmationStatus {
	if x != nil {
		return x.ConfirmationStatus
	}
	return ConfirmationStatus_CONFIRMATION_STATUS_UNSPECIFIED
}

func (x *AssetResponse) GetTracked() TrackedStatus {
	if x != nil {
		return x.Tracked
	}
	return TrackedStatus_TRACKED_STATUS_UNSPECIFIED
}

func (x *AssetResponse) GetAccessPolicy() map[string]*attribute.Attribute {
	if x != nil {
		return x.AccessPolicy
	}
	return nil
}

func (x *AssetResponse) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *AssetResponse) GetAtTime() *timestamppb.Timestamp {
	if x != nil {
		return x.AtTime
	}
	return nil
}

func (x *AssetResponse) GetProofMechanism() ProofMechanism {
	if x != nil {
		return x.ProofMechanism
	}
	return ProofMechanism_PROOF_MECHANISM_UNSPECIFIED
}

func (x *AssetResponse) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *AssetResponse) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *AssetResponse) GetTenantIdentity() string {
	if x != nil {
		return x.TenantIdentity
	}
	return ""
}

var File_datatrails_common_api_assets_v2_assets_assetresponse_proto protoreflect.FileDescriptor

const file_datatrails_common_api_assets_v2_assets_assetresponse_proto_rawDesc = "" +
	"\n" +
	":datatrails-common-api/assets/v2/assets/assetresponse.proto\x12\farchivist.v2\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a2datatrails-common-api/assets/v2/assets/enums.proto\x1a<datatrails-common-api/attribute/v2/attribute/attribute.proto\"\xb7\x0f\n" +
	"\rAssetResponse\x12L\n" +
	"\bidentity\x18\x01 \x01(\tB0\x92A-2)relative resource address `assets/{UUID}`@\x01R\bidentity\x12N\n" +
	"\n" +
	"behaviours\x18\x02 \x03(\tB.\x92A+2)list of behaviours enabled for this assetR\n" +
	"behaviours\x12w\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2+.archivist.v2.AssetResponse.AttributesEntryB*\x92A'2%key value mapping of asset propertiesR\n" +
	"attributes\x12\xa5\x01\n" +
	"\x13confirmation_status\x18\x04 \x01(\x0e2 .archivist.v2.ConfirmationStatusBR\x92AO2Gindicates if the asset has been succesfully committed to the blockchain@\x01\x9a\x02\x01\aR\x12confirmationStatus\x12~\n" +
	"\atracked\x18\x05 \x01(\x0e2\x1b.archivist.v2.TrackedStatusBG\x92AD2<indicates whether asset is still being tracked in the system@\x01\x9a\x02\x01\aR\atracked\x12\x8b\x01\n" +
	"\raccess_policy\x18\x06 \x03(\v2-.archivist.v2.AssetResponse.AccessPolicyEntryB7\x92A422key value mapping of behaviour to private for keysR\faccessPolicy\x12>\n" +
	"\x05owner\x18\a \x01(\tB(\x92A%2!wallet address of the asset owner@\x01R\x05owner\x12a\n" +
	"\aat_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampB,\x92A)2%indicates time the asset data is from@\x01R\x06atTime\x12~\n" +
	"\x0fproof_mechanism\x18\n" +
	" \x01(\x0e2\x1c.archivist.v2.ProofMechanismB7\x92A42.the mechanism used to provide evidential proof\x9a\x02\x01\aR\x0eproofMechanism\x12W\n" +
	"\bchain_id\x18\v \x01(\tB<\x92A925chain id of the blockchain associated with this asset@\x01R\achainId\x12)\n" +
	"\x06public\x18\f \x01(\bB\x11\x92A\x0e2\fPublic assetR\x06public\x12c\n" +
	"\x0ftenant_identity\x18\r \x01(\tB:\x92A722Identity of the tenant the that created this assetx\x80\bR\x0etenantIdentity\x1aV\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.archivist.v2.AttributeR\x05value:\x028\x01\x1aX\n" +
	"\x11AccessPolicyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.archivist.v2.AttributeR\x05value:\x028\x01:\x81\x04\x92A\xfd\x03\n" +
	"\x1a2\x18This describes an Asset.2\xde\x03{ \"identity\": \"assets/add30235-1424-4fda-840a-d5ef82c4c96f\", \"behaviours\": [\"RecordEvidence\"], \"attributes\": {    \"arc_display_type\": \"Garden Fence\",    \"arc_display_name\": \"My Garden Fence\",    \"colour\": \"Plain wood\" }, \"confirmation_status\": \"PENDING\", \"tracked\": \"TRACKED\", \"owner\": \"0x601f5A7D3e6dcB55e87bf2F17bC8A27AaCD3511\",\"at_time\": \"2019-11-27T14:44:19Z\",\"proof_mechanism\": \"MERKLE_LOG\",\"public\": false,\"tenant_identity\": \"tenant/8e0b600c-8234-43e4-860c-e95bdcd695a9\" }J\x04\b\t\x10\n" +
	"R\x11storage_integrityBLZJgithub.com/datatrails/go-datatrails-common-api-gen/assets/v2/assets;assetsb\x06proto3"

var (
	file_datatrails_common_api_assets_v2_assets_assetresponse_proto_rawDescOnce sync.Once
	file_datatrails_common_api_assets_v2_assets_assetresponse_proto_rawDescData []byte
)

func file_datatrails_common_api_assets_v2_assets_assetresponse_proto_rawDescGZIP() []byte {
	file_datatrails_common_api_assets_v2_assets_assetresponse_proto_rawDescOnce.Do(func() {
		file_datatrails_common_api_assets_v2_assets_assetresponse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datatrails_common_api_assets_v2_assets_assetresponse_proto_rawDesc), len(file_datatrails_common_api_assets_v2_assets_assetresponse_proto_rawDesc)))
	})
	return file_datatrails_common_api_assets_v2_assets_assetresponse_proto_rawDescData
}

var file_datatrails_common_api_assets_v2_assets_assetresponse_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_datatrails_common_api_assets_v2_assets_assetresponse_proto_goTypes = []any{
	(*AssetResponse)(nil),         // 0: archivist.v2.AssetResponse
	nil,                           // 1: archivist.v2.AssetResponse.AttributesEntry
	nil,                           // 2: archivist.v2.AssetResponse.AccessPolicyEntry
	(ConfirmationStatus)(0),       // 3: archivist.v2.ConfirmationStatus
	(TrackedStatus)(0),            // 4: archivist.v2.TrackedStatus
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(ProofMechanism)(0),           // 6: archivist.v2.ProofMechanism
	(*attribute.Attribute)(nil),   // 7: archivist.v2.Attribute
}
var file_datatrails_common_api_assets_v2_assets_assetresponse_proto_depIdxs = []int32{
	1, // 0: archivist.v2.AssetResponse.attributes:type_name -> archivist.v2.AssetResponse.AttributesEntry
	3, // 1: archivist.v2.AssetResponse.confirmation_status:type_name -> archivist.v2.ConfirmationStatus
	4, // 2: archivist.v2.AssetResponse.tracked:type_name -> archivist.v2.TrackedStatus
	2, // 3: archivist.v2.AssetResponse.access_policy:type_name -> archivist.v2.AssetResponse.AccessPolicyEntry
	5, // 4: archivist.v2.AssetResponse.at_time:type_name -> google.protobuf.Timestamp
	6, // 5: archivist.v2.AssetResponse.proof_mechanism:type_name -> archivist.v2.ProofMechanism
	7, // 6: archivist.v2.AssetResponse.AttributesEntry.value:type_name -> archivist.v2.Attribute
	7, // 7: archivist.v2.AssetResponse.AccessPolicyEntry.value:type_name -> archivist.v2.Attribute
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_datatrails_common_api_assets_v2_assets_assetresponse_proto_init() }
func file_datatrails_common_api_assets_v2_assets_assetresponse_proto_init() {
	if File_datatrails_common_api_assets_v2_assets_assetresponse_proto != nil {
		return
	}
	file_datatrails_common_api_assets_v2_assets_enums_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datatrails_common_api_assets_v2_assets_assetresponse_proto_rawDesc), len(file_datatrails_common_api_assets_v2_assets_assetresponse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datatrails_common_api_assets_v2_assets_assetresponse_proto_goTypes,
		DependencyIndexes: file_datatrails_common_api_assets_v2_assets_assetresponse_proto_depIdxs,
		MessageInfos:      file_datatrails_common_api_assets_v2_assets_assetresponse_proto_msgTypes,
	}.Build()
	File_datatrails_common_api_assets_v2_assets_assetresponse_proto = out.File
	file_datatrails_common_api_assets_v2_assets_assetresponse_proto_goTypes = nil
	file_datatrails_common_api_assets_v2_assets_assetresponse_proto_depIdxs = nil
}
