// Maintainers, please refer to the style guide here:
//     https://developers.google.com/protocol-buffers/docs/style

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: datatrails-common-api/assets/v2/assets/createasset.proto

package assets

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	attribute "github.com/datatrails/go-datatrails-simplehash/go-datatrails-common-api-gen/attribute/v2/attribute"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAssetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// list of enabled behaviours
	Behaviours []string `protobuf:"bytes,1,rep,name=behaviours,proto3" json:"behaviours,omitempty"`
	// event attributes for the assets creation
	Attributes map[string]*attribute.Attribute `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// mechanism for evidential proof for Events on this Asset
	ProofMechanism ProofMechanism `protobuf:"varint,4,opt,name=proof_mechanism,json=proofMechanism,proto3,enum=archivist.v2.ProofMechanism" json:"proof_mechanism,omitempty"`
	ChainId        string         `protobuf:"bytes,5,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Public         bool           `protobuf:"varint,6,opt,name=public,proto3" json:"public,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAssetRequest) Reset() {
	*x = CreateAssetRequest{}
	mi := &file_datatrails_common_api_assets_v2_assets_createasset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssetRequest) ProtoMessage() {}

func (x *CreateAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datatrails_common_api_assets_v2_assets_createasset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssetRequest.ProtoReflect.Descriptor instead.
func (*CreateAssetRequest) Descriptor() ([]byte, []int) {
	return file_datatrails_common_api_assets_v2_assets_createasset_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAssetRequest) GetBehaviours() []string {
	if x != nil {
		return x.Behaviours
	}
	return nil
}

func (x *CreateAssetRequest) GetAttributes() map[string]*attribute.Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *CreateAssetRequest) GetProofMechanism() ProofMechanism {
	if x != nil {
		return x.ProofMechanism
	}
	return ProofMechanism_PROOF_MECHANISM_UNSPECIFIED
}

func (x *CreateAssetRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *CreateAssetRequest) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

var File_datatrails_common_api_assets_v2_assets_createasset_proto protoreflect.FileDescriptor

const file_datatrails_common_api_assets_v2_assets_createasset_proto_rawDesc = "" +
	"\n" +
	"8datatrails-common-api/assets/v2/assets/createasset.proto\x12\farchivist.v2\x1a\x17validate/validate.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a2datatrails-common-api/assets/v2/assets/enums.proto\x1a<datatrails-common-api/attribute/v2/attribute/attribute.proto\"\xb6\t\n" +
	"\x12CreateAssetRequest\x12^\n" +
	"\n" +
	"behaviours\x18\x01 \x03(\tB>\x92A.2)list of behaviours enabled for this assetx\x80\b\xfaB\n" +
	"\x92\x01\a\"\x05r\x03\x18\x80\bR\n" +
	"behaviours\x12\xed\x01\n" +
	"\n" +
	"attributes\x18\x02 \x03(\v20.archivist.v2.CreateAssetRequest.AttributesEntryB\x9a\x01\x92A*2%key value mapping of event attributesx\x80\b\xfaBj\x9a\x01g\"erc\x10\x01\x18\x80\b2X^[^[:cntrl:]]*?[^[[:cntrl:]]+?[^[:cntrl:]]$|^[^[:cntrl:]]$|^[^[:cntrl:]]*?[^][:cntrl:]]$\xba\x01\x01.R\n" +
	"attributes\x12\xa7\x01\n" +
	"\x0fproof_mechanism\x18\x04 \x01(\x0e2\x1c.archivist.v2.ProofMechanismB`\x92AU2Ospecify the mechanism used to provide evidential proof for Events on this Asset\x9a\x02\x01\a\xfaB\x05\x82\x01\x02\x10\x01R\x0eproofMechanism\x12`\n" +
	"\bchain_id\x18\x05 \x01(\tBE\x92A:25chain id of the blockchain associated with this assetx\x80\b\xfaB\x05r\x03\x18\x80\bR\achainId\x12\xb7\x01\n" +
	"\x06public\x18\x06 \x01(\bB\x9e\x01\x92A\x9a\x012\x97\x01Public asset. A public asset and all its events are visible to the general public.Sharing to specific organisations is not available for public assets.R\x06public\x1aV\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.archivist.v2.AttributeR\x05value:\x028\x01:\x98\x02\x92A\x94\x02\n" +
	"=2;This describes the body of a request to create a new Asset.2\xd2\x01{ \"behaviours\": [\"RecordEvidence\"], \"attributes\": {    \"arc_display_type\": \"Garden Fence\",    \"arc_display_name\": \"My Garden Fence\",    \"colour\": \"Plain wood\" }, \"proof_mechanism\": \"MERKLE_LOG\",\"public\": false}J\x04\b\x03\x10\x04R\x11storage_integrityBLZJgithub.com/datatrails/go-datatrails-common-api-gen/assets/v2/assets;assetsb\x06proto3"

var (
	file_datatrails_common_api_assets_v2_assets_createasset_proto_rawDescOnce sync.Once
	file_datatrails_common_api_assets_v2_assets_createasset_proto_rawDescData []byte
)

func file_datatrails_common_api_assets_v2_assets_createasset_proto_rawDescGZIP() []byte {
	file_datatrails_common_api_assets_v2_assets_createasset_proto_rawDescOnce.Do(func() {
		file_datatrails_common_api_assets_v2_assets_createasset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datatrails_common_api_assets_v2_assets_createasset_proto_rawDesc), len(file_datatrails_common_api_assets_v2_assets_createasset_proto_rawDesc)))
	})
	return file_datatrails_common_api_assets_v2_assets_createasset_proto_rawDescData
}

var file_datatrails_common_api_assets_v2_assets_createasset_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_datatrails_common_api_assets_v2_assets_createasset_proto_goTypes = []any{
	(*CreateAssetRequest)(nil),  // 0: archivist.v2.CreateAssetRequest
	nil,                         // 1: archivist.v2.CreateAssetRequest.AttributesEntry
	(ProofMechanism)(0),         // 2: archivist.v2.ProofMechanism
	(*attribute.Attribute)(nil), // 3: archivist.v2.Attribute
}
var file_datatrails_common_api_assets_v2_assets_createasset_proto_depIdxs = []int32{
	1, // 0: archivist.v2.CreateAssetRequest.attributes:type_name -> archivist.v2.CreateAssetRequest.AttributesEntry
	2, // 1: archivist.v2.CreateAssetRequest.proof_mechanism:type_name -> archivist.v2.ProofMechanism
	3, // 2: archivist.v2.CreateAssetRequest.AttributesEntry.value:type_name -> archivist.v2.Attribute
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_datatrails_common_api_assets_v2_assets_createasset_proto_init() }
func file_datatrails_common_api_assets_v2_assets_createasset_proto_init() {
	if File_datatrails_common_api_assets_v2_assets_createasset_proto != nil {
		return
	}
	file_datatrails_common_api_assets_v2_assets_enums_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datatrails_common_api_assets_v2_assets_createasset_proto_rawDesc), len(file_datatrails_common_api_assets_v2_assets_createasset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datatrails_common_api_assets_v2_assets_createasset_proto_goTypes,
		DependencyIndexes: file_datatrails_common_api_assets_v2_assets_createasset_proto_depIdxs,
		MessageInfos:      file_datatrails_common_api_assets_v2_assets_createasset_proto_msgTypes,
	}.Build()
	File_datatrails_common_api_assets_v2_assets_createasset_proto = out.File
	file_datatrails_common_api_assets_v2_assets_createasset_proto_goTypes = nil
	file_datatrails_common_api_assets_v2_assets_createasset_proto_depIdxs = nil
}
