// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: datatrails-common-api/assets/v2/assets/enums.proto

package assets

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfirmationStatus int32

const (
	ConfirmationStatus_CONFIRMATION_STATUS_UNSPECIFIED ConfirmationStatus = 0
	ConfirmationStatus_PENDING                         ConfirmationStatus = 1 // Not yet stored
	ConfirmationStatus_CONFIRMED                       ConfirmationStatus = 2 // A tree root including the event has been signed by DataTrails
	ConfirmationStatus_FAILED                          ConfirmationStatus = 3 // Permanent failure
	ConfirmationStatus_STORED                          ConfirmationStatus = 4 // In database, awaiting verifiable commitment
	ConfirmationStatus_COMMITTED                       ConfirmationStatus = 5 // The stored event is verifiable
	ConfirmationStatus_UNEQUIVOCAL                     ConfirmationStatus = 6 // Provable independent of DataTrails
)

// Enum value maps for ConfirmationStatus.
var (
	ConfirmationStatus_name = map[int32]string{
		0: "CONFIRMATION_STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "CONFIRMED",
		3: "FAILED",
		4: "STORED",
		5: "COMMITTED",
		6: "UNEQUIVOCAL",
	}
	ConfirmationStatus_value = map[string]int32{
		"CONFIRMATION_STATUS_UNSPECIFIED": 0,
		"PENDING":                         1,
		"CONFIRMED":                       2,
		"FAILED":                          3,
		"STORED":                          4,
		"COMMITTED":                       5,
		"UNEQUIVOCAL":                     6,
	}
)

func (x ConfirmationStatus) Enum() *ConfirmationStatus {
	p := new(ConfirmationStatus)
	*p = x
	return p
}

func (x ConfirmationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfirmationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_datatrails_common_api_assets_v2_assets_enums_proto_enumTypes[0].Descriptor()
}

func (ConfirmationStatus) Type() protoreflect.EnumType {
	return &file_datatrails_common_api_assets_v2_assets_enums_proto_enumTypes[0]
}

func (x ConfirmationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfirmationStatus.Descriptor instead.
func (ConfirmationStatus) EnumDescriptor() ([]byte, []int) {
	return file_datatrails_common_api_assets_v2_assets_enums_proto_rawDescGZIP(), []int{0}
}

type TrackedStatus int32

const (
	TrackedStatus_TRACKED_STATUS_UNSPECIFIED TrackedStatus = 0
	TrackedStatus_TRACKED                    TrackedStatus = 1
	TrackedStatus_NOT_TRACKED                TrackedStatus = 2
	TrackedStatus_ANY                        TrackedStatus = 3
)

// Enum value maps for TrackedStatus.
var (
	TrackedStatus_name = map[int32]string{
		0: "TRACKED_STATUS_UNSPECIFIED",
		1: "TRACKED",
		2: "NOT_TRACKED",
		3: "ANY",
	}
	TrackedStatus_value = map[string]int32{
		"TRACKED_STATUS_UNSPECIFIED": 0,
		"TRACKED":                    1,
		"NOT_TRACKED":                2,
		"ANY":                        3,
	}
)

func (x TrackedStatus) Enum() *TrackedStatus {
	p := new(TrackedStatus)
	*p = x
	return p
}

func (x TrackedStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrackedStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_datatrails_common_api_assets_v2_assets_enums_proto_enumTypes[1].Descriptor()
}

func (TrackedStatus) Type() protoreflect.EnumType {
	return &file_datatrails_common_api_assets_v2_assets_enums_proto_enumTypes[1]
}

func (x TrackedStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrackedStatus.Descriptor instead.
func (TrackedStatus) EnumDescriptor() ([]byte, []int) {
	return file_datatrails_common_api_assets_v2_assets_enums_proto_rawDescGZIP(), []int{1}
}

type ProofMechanism int32

const (
	ProofMechanism_PROOF_MECHANISM_UNSPECIFIED ProofMechanism = 0
	ProofMechanism_RESERVED1                   ProofMechanism = 1
	ProofMechanism_SIMPLE_HASH                 ProofMechanism = 2
	ProofMechanism_MERKLE_LOG                  ProofMechanism = 3
)

// Enum value maps for ProofMechanism.
var (
	ProofMechanism_name = map[int32]string{
		0: "PROOF_MECHANISM_UNSPECIFIED",
		1: "RESERVED1",
		2: "SIMPLE_HASH",
		3: "MERKLE_LOG",
	}
	ProofMechanism_value = map[string]int32{
		"PROOF_MECHANISM_UNSPECIFIED": 0,
		"RESERVED1":                   1,
		"SIMPLE_HASH":                 2,
		"MERKLE_LOG":                  3,
	}
)

func (x ProofMechanism) Enum() *ProofMechanism {
	p := new(ProofMechanism)
	*p = x
	return p
}

func (x ProofMechanism) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProofMechanism) Descriptor() protoreflect.EnumDescriptor {
	return file_datatrails_common_api_assets_v2_assets_enums_proto_enumTypes[2].Descriptor()
}

func (ProofMechanism) Type() protoreflect.EnumType {
	return &file_datatrails_common_api_assets_v2_assets_enums_proto_enumTypes[2]
}

func (x ProofMechanism) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProofMechanism.Descriptor instead.
func (ProofMechanism) EnumDescriptor() ([]byte, []int) {
	return file_datatrails_common_api_assets_v2_assets_enums_proto_rawDescGZIP(), []int{2}
}

type Privacy int32

const (
	Privacy_PRIVACY_UNSPECIFIED Privacy = 0
	Privacy_RESTRICTED          Privacy = 1
	Privacy_PUBLIC              Privacy = 2
)

// Enum value maps for Privacy.
var (
	Privacy_name = map[int32]string{
		0: "PRIVACY_UNSPECIFIED",
		1: "RESTRICTED",
		2: "PUBLIC",
	}
	Privacy_value = map[string]int32{
		"PRIVACY_UNSPECIFIED": 0,
		"RESTRICTED":          1,
		"PUBLIC":              2,
	}
)

func (x Privacy) Enum() *Privacy {
	p := new(Privacy)
	*p = x
	return p
}

func (x Privacy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Privacy) Descriptor() protoreflect.EnumDescriptor {
	return file_datatrails_common_api_assets_v2_assets_enums_proto_enumTypes[3].Descriptor()
}

func (Privacy) Type() protoreflect.EnumType {
	return &file_datatrails_common_api_assets_v2_assets_enums_proto_enumTypes[3]
}

func (x Privacy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Privacy.Descriptor instead.
func (Privacy) EnumDescriptor() ([]byte, []int) {
	return file_datatrails_common_api_assets_v2_assets_enums_proto_rawDescGZIP(), []int{3}
}

var File_datatrails_common_api_assets_v2_assets_enums_proto protoreflect.FileDescriptor

const file_datatrails_common_api_assets_v2_assets_enums_proto_rawDesc = "" +
	"\n" +
	"2datatrails-common-api/assets/v2/assets/enums.proto\x12\farchivist.v2*\x8d\x01\n" +
	"\x12ConfirmationStatus\x12#\n" +
	"\x1fCONFIRMATION_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\r\n" +
	"\tCONFIRMED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\n" +
	"\n" +
	"\x06STORED\x10\x04\x12\r\n" +
	"\tCOMMITTED\x10\x05\x12\x0f\n" +
	"\vUNEQUIVOCAL\x10\x06*V\n" +
	"\rTrackedStatus\x12\x1e\n" +
	"\x1aTRACKED_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aTRACKED\x10\x01\x12\x0f\n" +
	"\vNOT_TRACKED\x10\x02\x12\a\n" +
	"\x03ANY\x10\x03*a\n" +
	"\x0eProofMechanism\x12\x1f\n" +
	"\x1bPROOF_MECHANISM_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tRESERVED1\x10\x01\x12\x0f\n" +
	"\vSIMPLE_HASH\x10\x02\x12\x0e\n" +
	"\n" +
	"MERKLE_LOG\x10\x03*>\n" +
	"\aPrivacy\x12\x17\n" +
	"\x13PRIVACY_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"RESTRICTED\x10\x01\x12\n" +
	"\n" +
	"\x06PUBLIC\x10\x02BLZJgithub.com/datatrails/go-datatrails-common-api-gen/assets/v2/assets;assetsb\x06proto3"

var (
	file_datatrails_common_api_assets_v2_assets_enums_proto_rawDescOnce sync.Once
	file_datatrails_common_api_assets_v2_assets_enums_proto_rawDescData []byte
)

func file_datatrails_common_api_assets_v2_assets_enums_proto_rawDescGZIP() []byte {
	file_datatrails_common_api_assets_v2_assets_enums_proto_rawDescOnce.Do(func() {
		file_datatrails_common_api_assets_v2_assets_enums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datatrails_common_api_assets_v2_assets_enums_proto_rawDesc), len(file_datatrails_common_api_assets_v2_assets_enums_proto_rawDesc)))
	})
	return file_datatrails_common_api_assets_v2_assets_enums_proto_rawDescData
}

var file_datatrails_common_api_assets_v2_assets_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_datatrails_common_api_assets_v2_assets_enums_proto_goTypes = []any{
	(ConfirmationStatus)(0), // 0: archivist.v2.ConfirmationStatus
	(TrackedStatus)(0),      // 1: archivist.v2.TrackedStatus
	(ProofMechanism)(0),     // 2: archivist.v2.ProofMechanism
	(Privacy)(0),            // 3: archivist.v2.Privacy
}
var file_datatrails_common_api_assets_v2_assets_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_datatrails_common_api_assets_v2_assets_enums_proto_init() }
func file_datatrails_common_api_assets_v2_assets_enums_proto_init() {
	if File_datatrails_common_api_assets_v2_assets_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datatrails_common_api_assets_v2_assets_enums_proto_rawDesc), len(file_datatrails_common_api_assets_v2_assets_enums_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datatrails_common_api_assets_v2_assets_enums_proto_goTypes,
		DependencyIndexes: file_datatrails_common_api_assets_v2_assets_enums_proto_depIdxs,
		EnumInfos:         file_datatrails_common_api_assets_v2_assets_enums_proto_enumTypes,
	}.Build()
	File_datatrails_common_api_assets_v2_assets_enums_proto = out.File
	file_datatrails_common_api_assets_v2_assets_enums_proto_goTypes = nil
	file_datatrails_common_api_assets_v2_assets_enums_proto_depIdxs = nil
}
