// Maintainers, please refer to the style guide here:
//     https://developers.google.com/protocol-buffers/docs/style

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: datatrails-common-api/assets/v2/assets/eventmessage.proto

package assets

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventMessage struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Event        *EventResponse         `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Asset        *AssetResponse         `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	TenantId     string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	FailedReason string                 `protobuf:"bytes,4,opt,name=failed_reason,json=failedReason,proto3" json:"failed_reason,omitempty"`
	// asset_create2_factory of the asset contract that exported the asset rlp
	// (from which the AssetResponse is made). identifies the asset contract
	// which enacted the change. The factory changes when the subjective value
	// chain membership changes, and if the factory itself needs upgrading
	// (which is very rare). So this value is a very clear (and easily
	// accessible) chain level record of who the SVC value chain colaborators
	// were when the change was made. All changes to an asset which share the
	// same factory can only have been enacted by a combination of the
	// privateFor's for whome the factory was deployed.
	AssetCreate2Factory string `protobuf:"bytes,5,opt,name=asset_create2_factory,json=assetCreate2Factory,proto3" json:"asset_create2_factory,omitempty"`
	// event_create2_factory of the behaviour contract that exported the event
	// rlp (from which the EventResponse is made). identifies the behaviour
	// contract which enacted the change. The factory changes when the
	// subjective value chain membership changes, and if the factory itself
	// needs upgrading (which is very rare)
	EventCreate2Factory string `protobuf:"bytes,6,opt,name=event_create2_factory,json=eventCreate2Factory,proto3" json:"event_create2_factory,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EventMessage) Reset() {
	*x = EventMessage{}
	mi := &file_datatrails_common_api_assets_v2_assets_eventmessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMessage) ProtoMessage() {}

func (x *EventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_datatrails_common_api_assets_v2_assets_eventmessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMessage.ProtoReflect.Descriptor instead.
func (*EventMessage) Descriptor() ([]byte, []int) {
	return file_datatrails_common_api_assets_v2_assets_eventmessage_proto_rawDescGZIP(), []int{0}
}

func (x *EventMessage) GetEvent() *EventResponse {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EventMessage) GetAsset() *AssetResponse {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *EventMessage) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EventMessage) GetFailedReason() string {
	if x != nil {
		return x.FailedReason
	}
	return ""
}

func (x *EventMessage) GetAssetCreate2Factory() string {
	if x != nil {
		return x.AssetCreate2Factory
	}
	return ""
}

func (x *EventMessage) GetEventCreate2Factory() string {
	if x != nil {
		return x.EventCreate2Factory
	}
	return ""
}

var File_datatrails_common_api_assets_v2_assets_eventmessage_proto protoreflect.FileDescriptor

const file_datatrails_common_api_assets_v2_assets_eventmessage_proto_rawDesc = "" +
	"\n" +
	"9datatrails-common-api/assets/v2/assets/eventmessage.proto\x12\farchivist.v2\x1a:datatrails-common-api/assets/v2/assets/eventresponse.proto\x1a:datatrails-common-api/assets/v2/assets/assetresponse.proto\"\x9e\x02\n" +
	"\fEventMessage\x121\n" +
	"\x05event\x18\x01 \x01(\v2\x1b.archivist.v2.EventResponseR\x05event\x121\n" +
	"\x05asset\x18\x02 \x01(\v2\x1b.archivist.v2.AssetResponseR\x05asset\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12#\n" +
	"\rfailed_reason\x18\x04 \x01(\tR\ffailedReason\x122\n" +
	"\x15asset_create2_factory\x18\x05 \x01(\tR\x13assetCreate2Factory\x122\n" +
	"\x15event_create2_factory\x18\x06 \x01(\tR\x13eventCreate2FactoryBLZJgithub.com/datatrails/go-datatrails-common-api-gen/assets/v2/assets;assetsb\x06proto3"

var (
	file_datatrails_common_api_assets_v2_assets_eventmessage_proto_rawDescOnce sync.Once
	file_datatrails_common_api_assets_v2_assets_eventmessage_proto_rawDescData []byte
)

func file_datatrails_common_api_assets_v2_assets_eventmessage_proto_rawDescGZIP() []byte {
	file_datatrails_common_api_assets_v2_assets_eventmessage_proto_rawDescOnce.Do(func() {
		file_datatrails_common_api_assets_v2_assets_eventmessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datatrails_common_api_assets_v2_assets_eventmessage_proto_rawDesc), len(file_datatrails_common_api_assets_v2_assets_eventmessage_proto_rawDesc)))
	})
	return file_datatrails_common_api_assets_v2_assets_eventmessage_proto_rawDescData
}

var file_datatrails_common_api_assets_v2_assets_eventmessage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_datatrails_common_api_assets_v2_assets_eventmessage_proto_goTypes = []any{
	(*EventMessage)(nil),  // 0: archivist.v2.EventMessage
	(*EventResponse)(nil), // 1: archivist.v2.EventResponse
	(*AssetResponse)(nil), // 2: archivist.v2.AssetResponse
}
var file_datatrails_common_api_assets_v2_assets_eventmessage_proto_depIdxs = []int32{
	1, // 0: archivist.v2.EventMessage.event:type_name -> archivist.v2.EventResponse
	2, // 1: archivist.v2.EventMessage.asset:type_name -> archivist.v2.AssetResponse
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_datatrails_common_api_assets_v2_assets_eventmessage_proto_init() }
func file_datatrails_common_api_assets_v2_assets_eventmessage_proto_init() {
	if File_datatrails_common_api_assets_v2_assets_eventmessage_proto != nil {
		return
	}
	file_datatrails_common_api_assets_v2_assets_eventresponse_proto_init()
	file_datatrails_common_api_assets_v2_assets_assetresponse_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datatrails_common_api_assets_v2_assets_eventmessage_proto_rawDesc), len(file_datatrails_common_api_assets_v2_assets_eventmessage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datatrails_common_api_assets_v2_assets_eventmessage_proto_goTypes,
		DependencyIndexes: file_datatrails_common_api_assets_v2_assets_eventmessage_proto_depIdxs,
		MessageInfos:      file_datatrails_common_api_assets_v2_assets_eventmessage_proto_msgTypes,
	}.Build()
	File_datatrails_common_api_assets_v2_assets_eventmessage_proto = out.File
	file_datatrails_common_api_assets_v2_assets_eventmessage_proto_goTypes = nil
	file_datatrails_common_api_assets_v2_assets_eventmessage_proto_depIdxs = nil
}
