// Maintainers, please refer to the style guide here:
//     https://developers.google.com/protocol-buffers/docs/style

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: datatrails-common-api/assets/v2/assets/getasset.proto

package assets

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAssetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// asset identity
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	AtTime        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=at_time,json=atTime,proto3" json:"at_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetRequest) Reset() {
	*x = GetAssetRequest{}
	mi := &file_datatrails_common_api_assets_v2_assets_getasset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetRequest) ProtoMessage() {}

func (x *GetAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datatrails_common_api_assets_v2_assets_getasset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetRequest.ProtoReflect.Descriptor instead.
func (*GetAssetRequest) Descriptor() ([]byte, []int) {
	return file_datatrails_common_api_assets_v2_assets_getasset_proto_rawDescGZIP(), []int{0}
}

func (x *GetAssetRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetAssetRequest) GetAtTime() *timestamppb.Timestamp {
	if x != nil {
		return x.AtTime
	}
	return nil
}

type GetAssetPublicURLRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// asset identity
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetPublicURLRequest) Reset() {
	*x = GetAssetPublicURLRequest{}
	mi := &file_datatrails_common_api_assets_v2_assets_getasset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetPublicURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetPublicURLRequest) ProtoMessage() {}

func (x *GetAssetPublicURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datatrails_common_api_assets_v2_assets_getasset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetPublicURLRequest.ProtoReflect.Descriptor instead.
func (*GetAssetPublicURLRequest) Descriptor() ([]byte, []int) {
	return file_datatrails_common_api_assets_v2_assets_getasset_proto_rawDescGZIP(), []int{1}
}

func (x *GetAssetPublicURLRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_datatrails_common_api_assets_v2_assets_getasset_proto protoreflect.FileDescriptor

const file_datatrails_common_api_assets_v2_assets_getasset_proto_rawDesc = "" +
	"\n" +
	"5datatrails-common-api/assets/v2/assets/getasset.proto\x12\farchivist.v2\x1a\x17validate/validate.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xea\x02\n" +
	"\x0fGetAssetRequest\x12\xd0\x01\n" +
	"\x04uuid\x18\x01 \x01(\tB\xbb\x01\x92A\xaf\x012\xaa\x01Specify the Asset UUID where `assets/{uuid}` is the Asset Identity e.g. `add30235-1424-4fda-840a-d5ef82c4c96f` from Identity `assets/add30235-1424-4fda-840a-d5ef82c4c96f`@\x01\xfaB\x05r\x03\xb0\x01\x01R\x04uuid\x12\x83\x01\n" +
	"\aat_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampBN\x92AK2GSpecify time in the past to show asset data as it was at time specified@\x01R\x06atTime\"\xed\x01\n" +
	"\x18GetAssetPublicURLRequest\x12\xd0\x01\n" +
	"\x04uuid\x18\x01 \x01(\tB\xbb\x01\x92A\xaf\x012\xaa\x01Specify the Asset UUID where `assets/{uuid}` is the Asset Identity e.g. `add30235-1424-4fda-840a-d5ef82c4c96f` from Identity `assets/add30235-1424-4fda-840a-d5ef82c4c96f`@\x01\xfaB\x05r\x03\xb0\x01\x01R\x04uuidBLZJgithub.com/datatrails/go-datatrails-common-api-gen/assets/v2/assets;assetsb\x06proto3"

var (
	file_datatrails_common_api_assets_v2_assets_getasset_proto_rawDescOnce sync.Once
	file_datatrails_common_api_assets_v2_assets_getasset_proto_rawDescData []byte
)

func file_datatrails_common_api_assets_v2_assets_getasset_proto_rawDescGZIP() []byte {
	file_datatrails_common_api_assets_v2_assets_getasset_proto_rawDescOnce.Do(func() {
		file_datatrails_common_api_assets_v2_assets_getasset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datatrails_common_api_assets_v2_assets_getasset_proto_rawDesc), len(file_datatrails_common_api_assets_v2_assets_getasset_proto_rawDesc)))
	})
	return file_datatrails_common_api_assets_v2_assets_getasset_proto_rawDescData
}

var file_datatrails_common_api_assets_v2_assets_getasset_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_datatrails_common_api_assets_v2_assets_getasset_proto_goTypes = []any{
	(*GetAssetRequest)(nil),          // 0: archivist.v2.GetAssetRequest
	(*GetAssetPublicURLRequest)(nil), // 1: archivist.v2.GetAssetPublicURLRequest
	(*timestamppb.Timestamp)(nil),    // 2: google.protobuf.Timestamp
}
var file_datatrails_common_api_assets_v2_assets_getasset_proto_depIdxs = []int32{
	2, // 0: archivist.v2.GetAssetRequest.at_time:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_datatrails_common_api_assets_v2_assets_getasset_proto_init() }
func file_datatrails_common_api_assets_v2_assets_getasset_proto_init() {
	if File_datatrails_common_api_assets_v2_assets_getasset_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datatrails_common_api_assets_v2_assets_getasset_proto_rawDesc), len(file_datatrails_common_api_assets_v2_assets_getasset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datatrails_common_api_assets_v2_assets_getasset_proto_goTypes,
		DependencyIndexes: file_datatrails_common_api_assets_v2_assets_getasset_proto_depIdxs,
		MessageInfos:      file_datatrails_common_api_assets_v2_assets_getasset_proto_msgTypes,
	}.Build()
	File_datatrails_common_api_assets_v2_assets_getasset_proto = out.File
	file_datatrails_common_api_assets_v2_assets_getasset_proto_goTypes = nil
	file_datatrails_common_api_assets_v2_assets_getasset_proto_depIdxs = nil
}
