// Maintainers, please refer to the style guide here:
//     https://developers.google.com/protocol-buffers/docs/style

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: datatrails-common-api/assets/v2/assets/getevent.proto

package assets

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetUuid     string                 `protobuf:"bytes,1,opt,name=asset_uuid,json=assetUuid,proto3" json:"asset_uuid,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_datatrails_common_api_assets_v2_assets_getevent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datatrails_common_api_assets_v2_assets_getevent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_datatrails_common_api_assets_v2_assets_getevent_proto_rawDescGZIP(), []int{0}
}

func (x *GetEventRequest) GetAssetUuid() string {
	if x != nil {
		return x.AssetUuid
	}
	return ""
}

func (x *GetEventRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_datatrails_common_api_assets_v2_assets_getevent_proto protoreflect.FileDescriptor

const file_datatrails_common_api_assets_v2_assets_getevent_proto_rawDesc = "" +
	"\n" +
	"5datatrails-common-api/assets/v2/assets/getevent.proto\x12\farchivist.v2\x1a\x17validate/validate.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xbe\x04\n" +
	"\x0fGetEventRequest\x12\x99\x02\n" +
	"\n" +
	"asset_uuid\x18\x01 \x01(\tB\xf9\x01\x92A\xed\x012\xea\x01Specify the Asset UUID where `assets/{asset_uuid}/events/{uuid}` is the Event Identity e.g. `add30235-1424-4fda-840a-d5ef82c4c96f` from Identity `assets/add30235-1424-4fda-840a-d5ef82c4c96f/events/11bf5b37-e0b8-42e0-8dcf-dc8c4aefc000`\xfaB\x05r\x03\xb0\x01\x01R\tassetUuid\x12\x8e\x02\n" +
	"\x04uuid\x18\x02 \x01(\tB\xf9\x01\x92A\xed\x012\xea\x01Specify the Event UUID where `assets/{asset_uuid}/events/{uuid}` is the Event Identity e.g. `11bf5b37-e0b8-42e0-8dcf-dc8c4aefc000` from Identity `assets/add30235-1424-4fda-840a-d5ef82c4c96f/events/11bf5b37-e0b8-42e0-8dcf-dc8c4aefc000`\xfaB\x05r\x03\xb0\x01\x01R\x04uuidBLZJgithub.com/datatrails/go-datatrails-common-api-gen/assets/v2/assets;assetsb\x06proto3"

var (
	file_datatrails_common_api_assets_v2_assets_getevent_proto_rawDescOnce sync.Once
	file_datatrails_common_api_assets_v2_assets_getevent_proto_rawDescData []byte
)

func file_datatrails_common_api_assets_v2_assets_getevent_proto_rawDescGZIP() []byte {
	file_datatrails_common_api_assets_v2_assets_getevent_proto_rawDescOnce.Do(func() {
		file_datatrails_common_api_assets_v2_assets_getevent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datatrails_common_api_assets_v2_assets_getevent_proto_rawDesc), len(file_datatrails_common_api_assets_v2_assets_getevent_proto_rawDesc)))
	})
	return file_datatrails_common_api_assets_v2_assets_getevent_proto_rawDescData
}

var file_datatrails_common_api_assets_v2_assets_getevent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_datatrails_common_api_assets_v2_assets_getevent_proto_goTypes = []any{
	(*GetEventRequest)(nil), // 0: archivist.v2.GetEventRequest
}
var file_datatrails_common_api_assets_v2_assets_getevent_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_datatrails_common_api_assets_v2_assets_getevent_proto_init() }
func file_datatrails_common_api_assets_v2_assets_getevent_proto_init() {
	if File_datatrails_common_api_assets_v2_assets_getevent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datatrails_common_api_assets_v2_assets_getevent_proto_rawDesc), len(file_datatrails_common_api_assets_v2_assets_getevent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datatrails_common_api_assets_v2_assets_getevent_proto_goTypes,
		DependencyIndexes: file_datatrails_common_api_assets_v2_assets_getevent_proto_depIdxs,
		MessageInfos:      file_datatrails_common_api_assets_v2_assets_getevent_proto_msgTypes,
	}.Build()
	File_datatrails_common_api_assets_v2_assets_getevent_proto = out.File
	file_datatrails_common_api_assets_v2_assets_getevent_proto_goTypes = nil
	file_datatrails_common_api_assets_v2_assets_getevent_proto_depIdxs = nil
}
