// Maintainers, please refer to the style guide here:
//     https://developers.google.com/protocol-buffers/docs/style

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: datatrails-common-api/assets/v2/assets/listassets.proto

package assets

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	filter "github.com/datatrails/go-datatrails-simplehash/go-datatrails-common-api-gen/filter/v1/filter"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Supported sort orders
type ListAssetsRequest_OrderBy int32

const (
	ListAssetsRequest_DEFAULT      ListAssetsRequest_OrderBy = 0
	ListAssetsRequest_SIMPLEHASHV1 ListAssetsRequest_OrderBy = 1
	ListAssetsRequest_SIMPLEHASHV2 ListAssetsRequest_OrderBy = 2
)

// Enum value maps for ListAssetsRequest_OrderBy.
var (
	ListAssetsRequest_OrderBy_name = map[int32]string{
		0: "DEFAULT",
		1: "SIMPLEHASHV1",
		2: "SIMPLEHASHV2",
	}
	ListAssetsRequest_OrderBy_value = map[string]int32{
		"DEFAULT":      0,
		"SIMPLEHASHV1": 1,
		"SIMPLEHASHV2": 2,
	}
)

func (x ListAssetsRequest_OrderBy) Enum() *ListAssetsRequest_OrderBy {
	p := new(ListAssetsRequest_OrderBy)
	*p = x
	return p
}

func (x ListAssetsRequest_OrderBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListAssetsRequest_OrderBy) Descriptor() protoreflect.EnumDescriptor {
	return file_datatrails_common_api_assets_v2_assets_listassets_proto_enumTypes[0].Descriptor()
}

func (ListAssetsRequest_OrderBy) Type() protoreflect.EnumType {
	return &file_datatrails_common_api_assets_v2_assets_listassets_proto_enumTypes[0]
}

func (x ListAssetsRequest_OrderBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListAssetsRequest_OrderBy.Descriptor instead.
func (ListAssetsRequest_OrderBy) EnumDescriptor() ([]byte, []int) {
	return file_datatrails_common_api_assets_v2_assets_listassets_proto_rawDescGZIP(), []int{0, 0}
}

type ListAssetsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum results per page.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The next_page_token returned from a previous list request if any.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Specify the sort order for the results.
	OrderBy ListAssetsRequest_OrderBy `protobuf:"varint,3,opt,name=order_by,json=orderBy,proto3,enum=archivist.v2.ListAssetsRequest_OrderBy" json:"order_by,omitempty"`
	// indicates whether asset is still being tracked in the system
	Tracked TrackedStatus `protobuf:"varint,4,opt,name=tracked,proto3,enum=archivist.v2.TrackedStatus" json:"tracked,omitempty"`
	// indicates if the asset has been succesfully committed to the blockchain
	ConfirmationStatus ConfirmationStatus `protobuf:"varint,5,opt,name=confirmation_status,json=confirmationStatus,proto3,enum=archivist.v2.ConfirmationStatus" json:"confirmation_status,omitempty"`
	// user defined attributes key max_length: 1024 value max_length: 4096
	Attributes map[string]string `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// proof mechanism of the asset (and all its events)
	ProofMechanism ProofMechanism `protobuf:"varint,8,opt,name=proof_mechanism,json=proofMechanism,proto3,enum=archivist.v2.ProofMechanism" json:"proof_mechanism,omitempty"`
	ChainId        string         `protobuf:"bytes,9,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// Outer list AND, inner list INCLUSIVE OR, e.g. [[A, B], [A, B]] "(A OR B) in first position AND (A OR B) in second position (and anything after)"
	// The behaviour of these filters matches the filters available for
	// selecting assets in access policies:
	// On the Access Policy editor page in the UX wire frames, we see locations and a asset_types as two of the items to filter on. A policy that expresses “a policy for all door access readers in Basingstoke or Cambridge”
	// [
	//
	//	{ "or": ["location=basingstoke", "location=cambridge"] },
	//	{ "or": ["asset_type=door_access_reader"] }
	//
	// ]
	Filters []*filter.Filter `protobuf:"bytes,10,rep,name=filters,proto3" json:"filters,omitempty"`
	// privacy filter of the asset (and all its events)
	Privacy       Privacy `protobuf:"varint,12,opt,name=privacy,proto3,enum=archivist.v2.Privacy" json:"privacy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsRequest) Reset() {
	*x = ListAssetsRequest{}
	mi := &file_datatrails_common_api_assets_v2_assets_listassets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsRequest) ProtoMessage() {}

func (x *ListAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datatrails_common_api_assets_v2_assets_listassets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsRequest.ProtoReflect.Descriptor instead.
func (*ListAssetsRequest) Descriptor() ([]byte, []int) {
	return file_datatrails_common_api_assets_v2_assets_listassets_proto_rawDescGZIP(), []int{0}
}

func (x *ListAssetsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAssetsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListAssetsRequest) GetOrderBy() ListAssetsRequest_OrderBy {
	if x != nil {
		return x.OrderBy
	}
	return ListAssetsRequest_DEFAULT
}

func (x *ListAssetsRequest) GetTracked() TrackedStatus {
	if x != nil {
		return x.Tracked
	}
	return TrackedStatus_TRACKED_STATUS_UNSPECIFIED
}

func (x *ListAssetsRequest) GetConfirmationStatus() ConfirmationStatus {
	if x != nil {
		return x.ConfirmationStatus
	}
	return ConfirmationStatus_CONFIRMATION_STATUS_UNSPECIFIED
}

func (x *ListAssetsRequest) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ListAssetsRequest) GetProofMechanism() ProofMechanism {
	if x != nil {
		return x.ProofMechanism
	}
	return ProofMechanism_PROOF_MECHANISM_UNSPECIFIED
}

func (x *ListAssetsRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ListAssetsRequest) GetFilters() []*filter.Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ListAssetsRequest) GetPrivacy() Privacy {
	if x != nil {
		return x.Privacy
	}
	return Privacy_PRIVACY_UNSPECIFIED
}

type ListAssetsResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Assets []*AssetResponse       `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	// Token to retrieve the next page of results or empty if there are none.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsResponse) Reset() {
	*x = ListAssetsResponse{}
	mi := &file_datatrails_common_api_assets_v2_assets_listassets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsResponse) ProtoMessage() {}

func (x *ListAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datatrails_common_api_assets_v2_assets_listassets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsResponse.ProtoReflect.Descriptor instead.
func (*ListAssetsResponse) Descriptor() ([]byte, []int) {
	return file_datatrails_common_api_assets_v2_assets_listassets_proto_rawDescGZIP(), []int{1}
}

func (x *ListAssetsResponse) GetAssets() []*AssetResponse {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *ListAssetsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_datatrails_common_api_assets_v2_assets_listassets_proto protoreflect.FileDescriptor

const file_datatrails_common_api_assets_v2_assets_listassets_proto_rawDesc = "" +
	"\n" +
	"7datatrails-common-api/assets/v2/assets/listassets.proto\x12\farchivist.v2\x1a\x17validate/validate.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a3datatrails-common-api/filter/v1/filter/filter.proto\x1a2datatrails-common-api/assets/v2/assets/enums.proto\x1a:datatrails-common-api/assets/v2/assets/assetresponse.proto\"\xca\a\n" +
	"\x11ListAssetsRequest\x12$\n" +
	"\tpage_size\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12B\n" +
	"\border_by\x18\x03 \x01(\x0e2'.archivist.v2.ListAssetsRequest.OrderByR\aorderBy\x125\n" +
	"\atracked\x18\x04 \x01(\x0e2\x1b.archivist.v2.TrackedStatusR\atracked\x12Q\n" +
	"\x13confirmation_status\x18\x05 \x01(\x0e2 .archivist.v2.ConfirmationStatusR\x12confirmationStatus\x12\x8d\x01\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2/.archivist.v2.ListAssetsRequest.AttributesEntryB<\x92A\x192\x17user defined attributes\xfaB\x1d\x9a\x01\x1a\"\x18r\x16\x10\x01\x18\x80\b2\x0f^[^[:cntrl:]]+$R\n" +
	"attributes\x12z\n" +
	"\x0fproof_mechanism\x18\b \x01(\x0e2\x1c.archivist.v2.ProofMechanismB3\x92A02.the mechanism used to provide evidential proofR\x0eproofMechanism\x12W\n" +
	"\bchain_id\x18\t \x01(\tB<\x92A925chain id of the blockchain associated with this asset@\x01R\achainId\x12<\n" +
	"\afilters\x18\n" +
	" \x03(\v2\x14.archivist.v1.FilterB\f\x92A\t2\afiltersR\afilters\x12]\n" +
	"\aprivacy\x18\f \x01(\x0e2\x15.archivist.v2.PrivacyB,\x92A!2\x1fthe privacy status of the asset\xfaB\x05\x82\x01\x02\x10\x01R\aprivacy\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\aOrderBy\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\x10\n" +
	"\fSIMPLEHASHV1\x10\x01\x12\x10\n" +
	"\fSIMPLEHASHV2\x10\x02J\x04\b\a\x10\bJ\x04\b\v\x10\fR\x11storage_integrityR\x06public\"\xf9\v\n" +
	"\x12ListAssetsResponse\x123\n" +
	"\x06assets\x18\x01 \x03(\v2\x1b.archivist.v2.AssetResponseR\x06assets\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken:\x85\v\x92A\x81\v\n" +
	"523A list of assets returned data identical to `Asset`2\xc7\n" +
	"{   \"assets\": [       {           \"identity\": \"assets/add30235-1424-4fda-840a-d5ef82c4c96f\",            \"behaviours\": [\"RecordEvidence\"],            \"attributes\": {                \"arc_display_type\": \"Garden Fence\",                \"arc_display_name\": \"My Garden Fence\",                \"colour\": \"Plain wood\"           },            \"confirmation_status\": \"PENDING\",            \"tracked\": \"TRACKED\",            \"owner\": \"0x601f5A7D3e6dcB55e87bf2F17bC8A27AaCD3511\",           \"at_time\": \"2019-11-27T14:44:19Z\",            \"proof_mechanism\": \"MERKLE_LOG\",           \"public\": false,           \"tenant_identity\": \"tenant/8e0b600c-8234-43e4-860c-e95bdcd695a9\"        },       {           \"identity\": \"assets/cef61346-2453-5aeb-921c-e6fa93d5b032\",            \"behaviours\": [\"RecordEvidence\"],            \"attributes\": {                \"arc_display_type\": \"IoT Device\",                \"arc_display_name\": \"My IoT Device\",                \"arc_firmware_version\": \"3.2.1\"           },            \"confirmation_status\": \"PENDING\",            \"tracked\": \"TRACKED\",            \"owner\": \"0x601f5A7D3e6dcB55e87bf2F17bC8A27AaCD3511\",           \"at_time\": \"2019-11-27T14:44:19Z\",            \"proof_mechanism\": \"MERKLE_LOG\",           \"public\": false,           \"tenant_identity\": \"tenant/8e0b600c-8234-43e4-860c-e95bdcd695a9\"        }   ],   \"next_page_token\": \"abcd\"}BLZJgithub.com/datatrails/go-datatrails-common-api-gen/assets/v2/assets;assetsb\x06proto3"

var (
	file_datatrails_common_api_assets_v2_assets_listassets_proto_rawDescOnce sync.Once
	file_datatrails_common_api_assets_v2_assets_listassets_proto_rawDescData []byte
)

func file_datatrails_common_api_assets_v2_assets_listassets_proto_rawDescGZIP() []byte {
	file_datatrails_common_api_assets_v2_assets_listassets_proto_rawDescOnce.Do(func() {
		file_datatrails_common_api_assets_v2_assets_listassets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datatrails_common_api_assets_v2_assets_listassets_proto_rawDesc), len(file_datatrails_common_api_assets_v2_assets_listassets_proto_rawDesc)))
	})
	return file_datatrails_common_api_assets_v2_assets_listassets_proto_rawDescData
}

var file_datatrails_common_api_assets_v2_assets_listassets_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_datatrails_common_api_assets_v2_assets_listassets_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_datatrails_common_api_assets_v2_assets_listassets_proto_goTypes = []any{
	(ListAssetsRequest_OrderBy)(0), // 0: archivist.v2.ListAssetsRequest.OrderBy
	(*ListAssetsRequest)(nil),      // 1: archivist.v2.ListAssetsRequest
	(*ListAssetsResponse)(nil),     // 2: archivist.v2.ListAssetsResponse
	nil,                            // 3: archivist.v2.ListAssetsRequest.AttributesEntry
	(TrackedStatus)(0),             // 4: archivist.v2.TrackedStatus
	(ConfirmationStatus)(0),        // 5: archivist.v2.ConfirmationStatus
	(ProofMechanism)(0),            // 6: archivist.v2.ProofMechanism
	(*filter.Filter)(nil),          // 7: archivist.v1.Filter
	(Privacy)(0),                   // 8: archivist.v2.Privacy
	(*AssetResponse)(nil),          // 9: archivist.v2.AssetResponse
}
var file_datatrails_common_api_assets_v2_assets_listassets_proto_depIdxs = []int32{
	0, // 0: archivist.v2.ListAssetsRequest.order_by:type_name -> archivist.v2.ListAssetsRequest.OrderBy
	4, // 1: archivist.v2.ListAssetsRequest.tracked:type_name -> archivist.v2.TrackedStatus
	5, // 2: archivist.v2.ListAssetsRequest.confirmation_status:type_name -> archivist.v2.ConfirmationStatus
	3, // 3: archivist.v2.ListAssetsRequest.attributes:type_name -> archivist.v2.ListAssetsRequest.AttributesEntry
	6, // 4: archivist.v2.ListAssetsRequest.proof_mechanism:type_name -> archivist.v2.ProofMechanism
	7, // 5: archivist.v2.ListAssetsRequest.filters:type_name -> archivist.v1.Filter
	8, // 6: archivist.v2.ListAssetsRequest.privacy:type_name -> archivist.v2.Privacy
	9, // 7: archivist.v2.ListAssetsResponse.assets:type_name -> archivist.v2.AssetResponse
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_datatrails_common_api_assets_v2_assets_listassets_proto_init() }
func file_datatrails_common_api_assets_v2_assets_listassets_proto_init() {
	if File_datatrails_common_api_assets_v2_assets_listassets_proto != nil {
		return
	}
	file_datatrails_common_api_assets_v2_assets_enums_proto_init()
	file_datatrails_common_api_assets_v2_assets_assetresponse_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datatrails_common_api_assets_v2_assets_listassets_proto_rawDesc), len(file_datatrails_common_api_assets_v2_assets_listassets_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datatrails_common_api_assets_v2_assets_listassets_proto_goTypes,
		DependencyIndexes: file_datatrails_common_api_assets_v2_assets_listassets_proto_depIdxs,
		EnumInfos:         file_datatrails_common_api_assets_v2_assets_listassets_proto_enumTypes,
		MessageInfos:      file_datatrails_common_api_assets_v2_assets_listassets_proto_msgTypes,
	}.Build()
	File_datatrails_common_api_assets_v2_assets_listassets_proto = out.File
	file_datatrails_common_api_assets_v2_assets_listassets_proto_goTypes = nil
	file_datatrails_common_api_assets_v2_assets_listassets_proto_depIdxs = nil
}
