// Maintainers, please refer to the style guide here:
//     https://developers.google.com/protocol-buffers/docs/style

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: datatrails-common-api/assets/v2/assets/principal.proto

package assets

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Principal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Principal) Reset() {
	*x = Principal{}
	mi := &file_datatrails_common_api_assets_v2_assets_principal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Principal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Principal) ProtoMessage() {}

func (x *Principal) ProtoReflect() protoreflect.Message {
	mi := &file_datatrails_common_api_assets_v2_assets_principal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Principal.ProtoReflect.Descriptor instead.
func (*Principal) Descriptor() ([]byte, []int) {
	return file_datatrails_common_api_assets_v2_assets_principal_proto_rawDescGZIP(), []int{0}
}

func (x *Principal) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *Principal) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Principal) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Principal) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_datatrails_common_api_assets_v2_assets_principal_proto protoreflect.FileDescriptor

const file_datatrails_common_api_assets_v2_assets_principal_proto_rawDesc = "" +
	"\n" +
	"6datatrails-common-api/assets/v2/assets/principal.proto\x12\farchivist.v2\x1a\x17validate/validate.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xc3\a\n" +
	"\tPrincipal\x12\x9c\x01\n" +
	"\x06issuer\x18\x01 \x01(\tB\x83\x01\x92Ax2soptional issuer of the principal identity. Where the issuer is not provided the subject is treated as a free stringx\x80\b\xfaB\x05r\x03\x18\x80\bR\x06issuer\x12d\n" +
	"\asubject\x18\x02 \x01(\tBJ\x92A?2:unique identifier of the principal (within issuer context)x\x80\b\xfaB\x05r\x03\x18\x80\bR\asubject\x12\xcc\x01\n" +
	"\fdisplay_name\x18\x03 \x01(\tB\xa8\x01\x92A\x9c\x012\x96\x01The displayable name of the end-user.  The name claim is prefered, followed by email claims, then a composite of  given_name, middle_name, family_namex\x80\b\xfaB\x05r\x03\x18\x80\bR\vdisplayName\x12\xc2\x01\n" +
	"\x05email\x18\x04 \x01(\tB\xab\x01\x92A\x9f\x012\x99\x01The email for the end-user if available. If email_verified is  available it is preferd. Empty if neither email_verified or email  are provided by the IdPx\x80\b\xfaB\x05r\x03\x18\x80\bR\x05email:\x9c\x02\x92A\x98\x02\n" +
	"\xdb\x012\xd8\x01The principal description assured by the configured Identity  Provider. All values are according to OIDC id token claims and  standard claims.  See https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims28{ \"issuer\": \"job.idp.server/1234\", \"subject\": \"bob@job\"}BLZJgithub.com/datatrails/go-datatrails-common-api-gen/assets/v2/assets;assetsb\x06proto3"

var (
	file_datatrails_common_api_assets_v2_assets_principal_proto_rawDescOnce sync.Once
	file_datatrails_common_api_assets_v2_assets_principal_proto_rawDescData []byte
)

func file_datatrails_common_api_assets_v2_assets_principal_proto_rawDescGZIP() []byte {
	file_datatrails_common_api_assets_v2_assets_principal_proto_rawDescOnce.Do(func() {
		file_datatrails_common_api_assets_v2_assets_principal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datatrails_common_api_assets_v2_assets_principal_proto_rawDesc), len(file_datatrails_common_api_assets_v2_assets_principal_proto_rawDesc)))
	})
	return file_datatrails_common_api_assets_v2_assets_principal_proto_rawDescData
}

var file_datatrails_common_api_assets_v2_assets_principal_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_datatrails_common_api_assets_v2_assets_principal_proto_goTypes = []any{
	(*Principal)(nil), // 0: archivist.v2.Principal
}
var file_datatrails_common_api_assets_v2_assets_principal_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_datatrails_common_api_assets_v2_assets_principal_proto_init() }
func file_datatrails_common_api_assets_v2_assets_principal_proto_init() {
	if File_datatrails_common_api_assets_v2_assets_principal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datatrails_common_api_assets_v2_assets_principal_proto_rawDesc), len(file_datatrails_common_api_assets_v2_assets_principal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datatrails_common_api_assets_v2_assets_principal_proto_goTypes,
		DependencyIndexes: file_datatrails_common_api_assets_v2_assets_principal_proto_depIdxs,
		MessageInfos:      file_datatrails_common_api_assets_v2_assets_principal_proto_msgTypes,
	}.Build()
	File_datatrails_common_api_assets_v2_assets_principal_proto = out.File
	file_datatrails_common_api_assets_v2_assets_principal_proto_goTypes = nil
	file_datatrails_common_api_assets_v2_assets_principal_proto_depIdxs = nil
}
