// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: datatrails-common-api/caps/v1/caps/caps.proto

//
// Caps messages
//

package caps

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCapsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapsRequest) Reset() {
	*x = GetCapsRequest{}
	mi := &file_datatrails_common_api_caps_v1_caps_caps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapsRequest) ProtoMessage() {}

func (x *GetCapsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datatrails_common_api_caps_v1_caps_caps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapsRequest.ProtoReflect.Descriptor instead.
func (*GetCapsRequest) Descriptor() ([]byte, []int) {
	return file_datatrails_common_api_caps_v1_caps_caps_proto_rawDescGZIP(), []int{0}
}

type Cap struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ResourceType      string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceRemaining int64                  `protobuf:"varint,2,opt,name=resource_remaining,json=resourceRemaining,proto3" json:"resource_remaining,omitempty"`
	ResourceCap       int64                  `protobuf:"varint,3,opt,name=resource_cap,json=resourceCap,proto3" json:"resource_cap,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Cap) Reset() {
	*x = Cap{}
	mi := &file_datatrails_common_api_caps_v1_caps_caps_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cap) ProtoMessage() {}

func (x *Cap) ProtoReflect() protoreflect.Message {
	mi := &file_datatrails_common_api_caps_v1_caps_caps_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cap.ProtoReflect.Descriptor instead.
func (*Cap) Descriptor() ([]byte, []int) {
	return file_datatrails_common_api_caps_v1_caps_caps_proto_rawDescGZIP(), []int{1}
}

func (x *Cap) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *Cap) GetResourceRemaining() int64 {
	if x != nil {
		return x.ResourceRemaining
	}
	return 0
}

func (x *Cap) GetResourceCap() int64 {
	if x != nil {
		return x.ResourceCap
	}
	return 0
}

type Caps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caps          []*Cap                 `protobuf:"bytes,1,rep,name=caps,proto3" json:"caps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Caps) Reset() {
	*x = Caps{}
	mi := &file_datatrails_common_api_caps_v1_caps_caps_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Caps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Caps) ProtoMessage() {}

func (x *Caps) ProtoReflect() protoreflect.Message {
	mi := &file_datatrails_common_api_caps_v1_caps_caps_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Caps.ProtoReflect.Descriptor instead.
func (*Caps) Descriptor() ([]byte, []int) {
	return file_datatrails_common_api_caps_v1_caps_caps_proto_rawDescGZIP(), []int{2}
}

func (x *Caps) GetCaps() []*Cap {
	if x != nil {
		return x.Caps
	}
	return nil
}

var File_datatrails_common_api_caps_v1_caps_caps_proto protoreflect.FileDescriptor

const file_datatrails_common_api_caps_v1_caps_caps_proto_rawDesc = "" +
	"\n" +
	"-datatrails-common-api/caps/v1/caps/caps.proto\x12\farchivist.v1\x1a\x17validate/validate.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"P\n" +
	"\x0eGetCapsRequest:>\x92A;\n" +
	"927GET Request for remaining capped resource. Placeholder.\"\x96\x02\n" +
	"\x03Cap\x12_\n" +
	"\rresource_type\x18\x01 \x01(\tB:\x92A-2+String identifying the capped resource type\xfaB\ar\x05\x10\x01\x18\x80\bR\fresourceType\x12h\n" +
	"\x12resource_remaining\x18\x02 \x01(\x03B9\x92A&2$Number of capped resources remaining\xfaB\r\"\v(\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01R\x11resourceRemaining\x12D\n" +
	"\fresource_cap\x18\x03 \x01(\x03B!\x92A\x0e2\fResource cap\xfaB\r\"\v(\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01R\vresourceCap\"U\n" +
	"\x04Caps\x12M\n" +
	"\x04caps\x18\x01 \x03(\v2\x11.archivist.v1.CapB&\x92A#2!List of relevant capped resourcesR\x04capsBFZDgithub.com/datatrails/go-datatrails-common-api-gen/caps/v1/caps;capsb\x06proto3"

var (
	file_datatrails_common_api_caps_v1_caps_caps_proto_rawDescOnce sync.Once
	file_datatrails_common_api_caps_v1_caps_caps_proto_rawDescData []byte
)

func file_datatrails_common_api_caps_v1_caps_caps_proto_rawDescGZIP() []byte {
	file_datatrails_common_api_caps_v1_caps_caps_proto_rawDescOnce.Do(func() {
		file_datatrails_common_api_caps_v1_caps_caps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datatrails_common_api_caps_v1_caps_caps_proto_rawDesc), len(file_datatrails_common_api_caps_v1_caps_caps_proto_rawDesc)))
	})
	return file_datatrails_common_api_caps_v1_caps_caps_proto_rawDescData
}

var file_datatrails_common_api_caps_v1_caps_caps_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_datatrails_common_api_caps_v1_caps_caps_proto_goTypes = []any{
	(*GetCapsRequest)(nil), // 0: archivist.v1.GetCapsRequest
	(*Cap)(nil),            // 1: archivist.v1.Cap
	(*Caps)(nil),           // 2: archivist.v1.Caps
}
var file_datatrails_common_api_caps_v1_caps_caps_proto_depIdxs = []int32{
	1, // 0: archivist.v1.Caps.caps:type_name -> archivist.v1.Cap
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_datatrails_common_api_caps_v1_caps_caps_proto_init() }
func file_datatrails_common_api_caps_v1_caps_caps_proto_init() {
	if File_datatrails_common_api_caps_v1_caps_caps_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datatrails_common_api_caps_v1_caps_caps_proto_rawDesc), len(file_datatrails_common_api_caps_v1_caps_caps_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datatrails_common_api_caps_v1_caps_caps_proto_goTypes,
		DependencyIndexes: file_datatrails_common_api_caps_v1_caps_caps_proto_depIdxs,
		MessageInfos:      file_datatrails_common_api_caps_v1_caps_caps_proto_msgTypes,
	}.Build()
	File_datatrails_common_api_caps_v1_caps_caps_proto = out.File
	file_datatrails_common_api_caps_v1_caps_caps_proto_goTypes = nil
	file_datatrails_common_api_caps_v1_caps_caps_proto_depIdxs = nil
}
