// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: datatrails-common-api/attribute/v2/attribute/attribute.proto

//
// Structured attributes for attributes in assets and locations
//

package attribute

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DictAttr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         map[string]string      `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictAttr) Reset() {
	*x = DictAttr{}
	mi := &file_datatrails_common_api_attribute_v2_attribute_attribute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictAttr) ProtoMessage() {}

func (x *DictAttr) ProtoReflect() protoreflect.Message {
	mi := &file_datatrails_common_api_attribute_v2_attribute_attribute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictAttr.ProtoReflect.Descriptor instead.
func (*DictAttr) Descriptor() ([]byte, []int) {
	return file_datatrails_common_api_attribute_v2_attribute_attribute_proto_rawDescGZIP(), []int{0}
}

func (x *DictAttr) GetValue() map[string]string {
	if x != nil {
		return x.Value
	}
	return nil
}

type ListAttr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []*DictAttr            `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttr) Reset() {
	*x = ListAttr{}
	mi := &file_datatrails_common_api_attribute_v2_attribute_attribute_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttr) ProtoMessage() {}

func (x *ListAttr) ProtoReflect() protoreflect.Message {
	mi := &file_datatrails_common_api_attribute_v2_attribute_attribute_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttr.ProtoReflect.Descriptor instead.
func (*ListAttr) Descriptor() ([]byte, []int) {
	return file_datatrails_common_api_attribute_v2_attribute_attribute_proto_rawDescGZIP(), []int{1}
}

func (x *ListAttr) GetValue() []*DictAttr {
	if x != nil {
		return x.Value
	}
	return nil
}

type Attribute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Attribute_StrVal
	//	*Attribute_DictVal
	//	*Attribute_ListVal
	Value         isAttribute_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_datatrails_common_api_attribute_v2_attribute_attribute_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_datatrails_common_api_attribute_v2_attribute_attribute_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_datatrails_common_api_attribute_v2_attribute_attribute_proto_rawDescGZIP(), []int{2}
}

func (x *Attribute) GetValue() isAttribute_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Attribute) GetStrVal() string {
	if x != nil {
		if x, ok := x.Value.(*Attribute_StrVal); ok {
			return x.StrVal
		}
	}
	return ""
}

func (x *Attribute) GetDictVal() *DictAttr {
	if x != nil {
		if x, ok := x.Value.(*Attribute_DictVal); ok {
			return x.DictVal
		}
	}
	return nil
}

func (x *Attribute) GetListVal() *ListAttr {
	if x != nil {
		if x, ok := x.Value.(*Attribute_ListVal); ok {
			return x.ListVal
		}
	}
	return nil
}

type isAttribute_Value interface {
	isAttribute_Value()
}

type Attribute_StrVal struct {
	StrVal string `protobuf:"bytes,1,opt,name=str_val,json=strVal,proto3,oneof"`
}

type Attribute_DictVal struct {
	DictVal *DictAttr `protobuf:"bytes,2,opt,name=dict_val,json=dictVal,proto3,oneof"`
}

type Attribute_ListVal struct {
	ListVal *ListAttr `protobuf:"bytes,3,opt,name=list_val,json=listVal,proto3,oneof"`
}

func (*Attribute_StrVal) isAttribute_Value() {}

func (*Attribute_DictVal) isAttribute_Value() {}

func (*Attribute_ListVal) isAttribute_Value() {}

var File_datatrails_common_api_attribute_v2_attribute_attribute_proto protoreflect.FileDescriptor

const file_datatrails_common_api_attribute_v2_attribute_attribute_proto_rawDesc = "" +
	"\n" +
	"<datatrails-common-api/attribute/v2/attribute/attribute.proto\x12\farchivist.v2\x1a\x17validate/validate.proto\"\x97\x01\n" +
	"\bDictAttr\x12Q\n" +
	"\x05value\x18\x01 \x03(\v2!.archivist.v2.DictAttr.ValueEntryB\x18\xfaB\x15\x9a\x01\x12\"\tr\a\x18\x80\b\xba\x01\x01.*\x05r\x03\x18\x80 R\x05value\x1a8\n" +
	"\n" +
	"ValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\bListAttr\x12,\n" +
	"\x05value\x18\x01 \x03(\v2\x16.archivist.v2.DictAttrR\x05value\"\xa3\x01\n" +
	"\tAttribute\x12#\n" +
	"\astr_val\x18\x01 \x01(\tB\b\xfaB\x05r\x03\x18\x80 H\x00R\x06strVal\x123\n" +
	"\bdict_val\x18\x02 \x01(\v2\x16.archivist.v2.DictAttrH\x00R\adictVal\x123\n" +
	"\blist_val\x18\x03 \x01(\v2\x16.archivist.v2.ListAttrH\x00R\alistValB\a\n" +
	"\x05valueBUZSgithub.com/datatrails/go-datatrails-common-api-gen/attribute/v2/attribute;attributeb\x06proto3"

var (
	file_datatrails_common_api_attribute_v2_attribute_attribute_proto_rawDescOnce sync.Once
	file_datatrails_common_api_attribute_v2_attribute_attribute_proto_rawDescData []byte
)

func file_datatrails_common_api_attribute_v2_attribute_attribute_proto_rawDescGZIP() []byte {
	file_datatrails_common_api_attribute_v2_attribute_attribute_proto_rawDescOnce.Do(func() {
		file_datatrails_common_api_attribute_v2_attribute_attribute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datatrails_common_api_attribute_v2_attribute_attribute_proto_rawDesc), len(file_datatrails_common_api_attribute_v2_attribute_attribute_proto_rawDesc)))
	})
	return file_datatrails_common_api_attribute_v2_attribute_attribute_proto_rawDescData
}

var file_datatrails_common_api_attribute_v2_attribute_attribute_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_datatrails_common_api_attribute_v2_attribute_attribute_proto_goTypes = []any{
	(*DictAttr)(nil),  // 0: archivist.v2.DictAttr
	(*ListAttr)(nil),  // 1: archivist.v2.ListAttr
	(*Attribute)(nil), // 2: archivist.v2.Attribute
	nil,               // 3: archivist.v2.DictAttr.ValueEntry
}
var file_datatrails_common_api_attribute_v2_attribute_attribute_proto_depIdxs = []int32{
	3, // 0: archivist.v2.DictAttr.value:type_name -> archivist.v2.DictAttr.ValueEntry
	0, // 1: archivist.v2.ListAttr.value:type_name -> archivist.v2.DictAttr
	0, // 2: archivist.v2.Attribute.dict_val:type_name -> archivist.v2.DictAttr
	1, // 3: archivist.v2.Attribute.list_val:type_name -> archivist.v2.ListAttr
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_datatrails_common_api_attribute_v2_attribute_attribute_proto_init() }
func file_datatrails_common_api_attribute_v2_attribute_attribute_proto_init() {
	if File_datatrails_common_api_attribute_v2_attribute_attribute_proto != nil {
		return
	}
	file_datatrails_common_api_attribute_v2_attribute_attribute_proto_msgTypes[2].OneofWrappers = []any{
		(*Attribute_StrVal)(nil),
		(*Attribute_DictVal)(nil),
		(*Attribute_ListVal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datatrails_common_api_attribute_v2_attribute_attribute_proto_rawDesc), len(file_datatrails_common_api_attribute_v2_attribute_attribute_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datatrails_common_api_attribute_v2_attribute_attribute_proto_goTypes,
		DependencyIndexes: file_datatrails_common_api_attribute_v2_attribute_attribute_proto_depIdxs,
		MessageInfos:      file_datatrails_common_api_attribute_v2_attribute_attribute_proto_msgTypes,
	}.Build()
	File_datatrails_common_api_attribute_v2_attribute_attribute_proto = out.File
	file_datatrails_common_api_attribute_v2_attribute_attribute_proto_goTypes = nil
	file_datatrails_common_api_attribute_v2_attribute_attribute_proto_depIdxs = nil
}
