name: ci
on:
  push:
  release:
    types: [published]

jobs:
  test:
    name: Quality Control
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup go-task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.x'
          token: ${{ secrets.GITHUB_TOKEN }}
          cache-dependency-path: |
            datatrails-common-api/go.sum

      - name: Install Go quality tools
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "${PWD}/bin" v1.64.2
          echo "${PWD}/bin" >> $GITHUB_PATH

      - name: Code Quality 
        run: |
          # Note: it is by design that we don't use the builder
          task codeqa

      - name: Test
        run: |
          # Note: it is by design that we don't use the builder
          task test
